### PR TITLE
Use new commons with better mult app support

### PR DESCRIPTION
**Pull request by shirey**
- Changes to work with the commons
- Separate docker directories for HuBMAP and SenNet to share the same codebase

### CODE REVIEW

**Comment by yuanzhou** [comment]
Need to make corresponding/similar changes to the SenNet uuid-api repo

**Comment by shirey** [comment]
@yuanzhou SenNet uuid-api repo should be deleted.  uuid service should be able to be used with the same code base across multiple projects with different app.cfg configuration files.

**Comment by yuanzhou** [comment]
> @yuanzhou SenNet uuid-api repo should be deleted. uuid service should be able to be used with the same code base across multiple projects with different app.cfg configuration files.

Actually not, the docker build is specific to the SenNet project, we can't reuse the same HM repo even though the codebase is the almost same

**Review by yuanzhou — APPROVED** [review]
Looks good to me and we are testing the branch directly in SenNet. Will not merge until we are ready for the HuBMAP test.

**Review by kburke — APPROVED** [review]
I discussed the items Joe asked me to focus on with him, but I'll click Approve so I'm not holding up this PR.  My concerns about the contents of the sql directory have already been discussed, and are addressed by another branch.  I'm unsure if or how long requirements text should have git+https://github.com/hubmapconsortium/commons.git@shirey/refactor-mult-apps#egg=hubmap-commons.

**Comment by yuanzhou** [comment]
@kburke we'll make a corresponding release in commons once everything gets tested against these changes, and by then we'll publish a new commons to PyPI and remove the pip git install.

**Pull request merged**
